name: "Came Connect"
description: "Local REST proxy for CAME Connect"
version: "1.0.1"
slug: "came_connect"
startup: application
boot: auto
init: false

arch:
  - amd64

ports:
  8080/tcp: 9002

options:
  client_id: ""
  client_secret: ""
  username: ""
  password: ""
  device_id: ""

schema:
  client_id: str
  client_secret: str
  username: str
  password: password
  device_id: str
