name: "Came Connect - Proxmox edition"
description: "Local REST proxy for CAME Connect on x86 arch"
version: "1.2.15"
slug: "came_connect"
startup: services
boot: auto
init: false

arch:
  - amd64


ports:
  9002/tcp: 9002
options:
  client_secret: ""
  username: ""
  password: ""
  device_id: ""


schema:
  client_id: str
  client_secret: str
  username: str
  password: password
  device_id: str
